[theme]
base = "light"
primaryColor = "#326b5c"
backgroundColor = "#f8f6ee"
secondaryBackgroundColor = "#eaf0e9"
textColor = "#294b43"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
